### ISSUE TITLE
pygbif?

### ISSUE THREAD

**Issue by sckott** [jeffreysmith-jrs/testingEcoregions#1]
nice work on the paper, just saw that you cited an issue from the rgbif repo (I track through google scholar), and just wanted to drop a note for the future (clearly the paper is already out) that there's a python client for GBIF in case you hadn't seen it, including the download API which duplicates downloads you get from their website: https://pypi.org/project/pygbif/

**Comment by jeffreysmith-jrs** [comment]
Hi Scott,
Thanks for your comment - I have seen the python client and find it has been great when I've used it in the past. I hope to update a version of this code in the future so I will try to incorporate it then - thanks for the tip.
Jeff

**Comment by sckott** [comment]
Cool. don't mean to pressure at all, just in case you didn't know, but you do 😸

**Comment by jeffreysmith-jrs** [comment]
I'll take any help or tips I can get! 😀
